spring:
    datasource:
        url: jdbc:mysql://192.168.105.18:3306/idg_test_db?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: idg_test_db_user
        password: idg_test_db_user